
# window
background_opacity 0.85
background_blur 50

scrollback_lines 10000

# font
font_size 13

# dynamic_background_opacity yes
allow_remote_control yes

# disable kitty tab
map shift+cmd+t new_tab
map cmd+t no_op
