
# window
background_opacity 0.85
background_blur 50

scrollback_lines 10000
scrollback_pager nvim -u NONE -R -M -c 'lua require("integration.kitty")(INPUT_LINE_NUMBER, CURSOR_LINE, CURSOR_COLUMN)' -

include appearance.conf

# dynamic_background_opacity yes
allow_remote_control yes

# disable kitty tab
map shift+cmd+t new_tab
map cmd+t no_op
