let mapleader = "\<space>"

set scrolloff=10
set ignorecase smartcase
set showmode

set number relativenumber
syntax on

set clipboard+=unnamed
nnoremap yy "+yy
vnoremap y "+y
nnoremap p "+p
vnoremap p "+p
nnoremap P "+P
vnoremap P "+P
nnoremap <leader>yy yy
vnoremap <leader>y y
nnoremap <leader>p p
vnoremap <leader>p p
nnoremap <leader>P P
vnoremap <leader>P P
nnoremap <leader>dd "+dd
vnoremap <leader>d "+d


vmap U <C-R>
nmap U <C-R>

vmap H ^
vmap L $
nmap H ^
nmap L $

nmap J 3j
vmap J 3j
nmap K 3k
vmap K 3k

