[Metadata]
Name=dark-rounded
Version=1
Author=lumither
Description=Borderless rounded dark theme
ScaleWithDPI=True

[InputPanel]
NormalColor=#d8d8d4
HighlightCandidateColor=#ffffff
HighlightColor=#ffffff
HighlightBackgroundColor=#45453f
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=8
Right=8
Top=6
Bottom=6

[InputPanel/Background]
Image=panel.png

[InputPanel/Background/Margin]
Left=12
Right=12
Top=12
Bottom=12

[InputPanel/Highlight]
Image=highlight.png

[InputPanel/Highlight/Margin]
Left=8
Right=8
Top=5
Bottom=5

[InputPanel/PrevPage]
Image=prev.png

[InputPanel/NextPage]
Image=next.png

[Menu]
NormalColor=#d8d8d4
HighlightColor=#ffffff

[Menu/Background]
Image=panel.png

[Menu/Background/Margin]
Left=12
Right=12
Top=12
Bottom=12

[Menu/Highlight]
Image=highlight.png

[Menu/Highlight/Margin]
Left=8
Right=8
Top=5
Bottom=5

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/TextMargin]
Left=6
Right=6
Top=4
Bottom=4

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/Separator]
Color=#45453f
